name: mytrb
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+8

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  # Basic Flutter dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  responsive_framework: ^0.2.0

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Logging
  logger: ^2.0.2+1 # Log events clearly
  pretty_dio_logger: ^1.3.1 # API logging and debugging

  # Networking & API handling
  dio: ^5.4.1
  http_mock_adapter: ^0.6.1 # Mocking dio for testing
  upgrader: ^8.4.0

  # Storage & Persistence
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Location & Geolocation
  location: ^5.0.3
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # UI Components & Effects
  flutter_svg: ^2.0.10+1 # SVG icons
  smooth_page_indicator: ^1.1.0 # Onboarding screen
  flutter_spinkit: ^5.2.0 # Loading indicators
  cached_network_image: ^3.3.1 # Network image caching
  carousel_slider: ^4.2.1 # Image slider
  shimmer: ^3.0.0 # Shimmer effect
  step_progress_indicator: ^1.0.2 # Progress indicator
  lottie: ^2.0.6 # Lottie animations
  flutter_animate: ^4.5.0 # Animation package
  animate_do: ^3.1.2
  dynamic_color: ^1.6.2
  page_transition: ^2.0.9
  encrypt: ^5.0.1
  validators: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_typeahead: ^4.3.6
  html_editor_enhanced: ^2.5.1
  pull_to_refresh: ^2.0.0
  translator: ^1.0.3+1

  # Date & Time formatting
  intl: ^0.18.0

  # File Handling
  flutter_image_compress: ^2.3.0
  image_picker: ^1.0.7
  image: ^4.1.4
  path_provider: ^2.0.12

  # Device Info & Permissions
  device_info_plus: ^9.1.2
  device_imei: ^0.0.4+2
  permission_handler: ^11.0.0
  connectivity_plus: ^5.0.2
  local_auth: ^2.1.8

  # Notifications
  onesignal_flutter: ^5.2.6

  # Web & HTML Rendering
  webview_flutter: ^4.5.0
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  linkify: ^5.0.0
  url_launcher: ^6.2.1

  # PDF Viewing
  pdfx: ^2.6.0
  flutter_pdfview: ^1.3.2

  # Dialogs & Loaders
  flutter_dialogs: ^3.0.0
  flutter_easyloading: ^3.0.5

  # UI Elements
  dropdown_button2: ^2.3.9
  dots_indicator: ^3.0.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mytrb1.png"
  adaptive_icon_background: "#0D47A1"
  adaptive_icon_foreground: "assets/images/mytrb1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/dbs/
    - assets/vectors/
    - assets/fonts/
    - assets/data/
    - assets/animations/

fonts:
  - family: Citadelle
    fonts:
      - asset: assets/fonts/Citadelle_PersonalUseOnly.ttf
  - family: Inter
    fonts:
      - asset: assets/fonts/static/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/static/Inter-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/static/Inter-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/static/Inter-Light.ttf
        weight: 300
      - asset: assets/fonts/static/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/static/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/static/Inter-SemiBold.ttf
        weight: 600
